version: "3"

services:
  mongodb1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./volumes/mongodb1:/data/db
    ports:
      - "27011:27011"
    expose:
      - "27011"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27011",
        "--replSet", "rs0",
        "--bind_ip_all",
      ]

  mongosetup:
    container_name: mongosetup
    image: "mongo-setup"
    build: "./"
    depends_on:
      - mongodb1

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb1:27011/beanie_demo?replicaSet=rs0
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongodb1
      - mongosetup